//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kalus.Properties.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAMPSELECT.
        /// </summary>
        public static string CHAMPSELECT {
            get {
                return ResourceManager.GetString("CHAMPSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENT.
        /// </summary>
        public static string CLIENT {
            get {
                return ResourceManager.GetString("CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME.
        /// </summary>
        public static string GAME {
            get {
                return ResourceManager.GetString("GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMESTART.
        /// </summary>
        public static string GAMESTART {
            get {
                return ResourceManager.GetString("GAMESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KALUS.
        /// </summary>
        public static string KALUS {
            get {
                return ResourceManager.GetString("KALUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOBBY.
        /// </summary>
        public static string LOBBY {
            get {
                return ResourceManager.GetString("LOBBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHMAKING.
        /// </summary>
        public static string MATCHMAKING {
            get {
                return ResourceManager.GetString("MATCHMAKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOCLIENT.
        /// </summary>
        public static string NOCLIENT {
            get {
                return ResourceManager.GetString("NOCLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTPICK.
        /// </summary>
        public static string POSTPICK {
            get {
                return ResourceManager.GetString("POSTPICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY.
        /// </summary>
        public static string READY {
            get {
                return ResourceManager.GetString("READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READYCHECK.
        /// </summary>
        public static string READYCHECK {
            get {
                return ResourceManager.GetString("READYCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REROLL.
        /// </summary>
        public static string REROLL {
            get {
                return ResourceManager.GetString("REROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIN.
        /// </summary>
        public static string SKIN {
            get {
                return ResourceManager.GetString("SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAPPING.
        /// </summary>
        public static string SWAPPING {
            get {
                return ResourceManager.GetString("SWAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADE.
        /// </summary>
        public static string TRADE {
            get {
                return ResourceManager.GetString("TRADE", resourceCulture);
            }
        }
    }
}
