//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logs___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kalus.Properties.Logs - Copy", typeof(Logs___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerolled to .
        /// </summary>
        public static string AramReroll {
            get {
                return ResourceManager.GetString("AramReroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reroll was not better, retrieving last champion.
        /// </summary>
        public static string AramRetrieveChampion {
            get {
                return ResourceManager.GetString("AramRetrieveChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapped with .
        /// </summary>
        public static string AramSwap {
            get {
                return ResourceManager.GetString("AramSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending trade request.
        /// </summary>
        public static string AramTradeRequest {
            get {
                return ResourceManager.GetString("AramTradeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has been closed.
        /// </summary>
        public static string ClientClosed {
            get {
                return ResourceManager.GetString("ClientClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Found.
        /// </summary>
        public static string ClientFound {
            get {
                return ResourceManager.GetString("ClientFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured : .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined ARAM Game.
        /// </summary>
        public static string JoiningAram {
            get {
                return ResourceManager.GetString("JoiningAram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined .
        /// </summary>
        public static string JoiningClassicGame {
            get {
                return ResourceManager.GetString("JoiningClassicGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KALUS is ready.
        /// </summary>
        public static string KALUSReady {
            get {
                return ResourceManager.GetString("KALUSReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking random skin.
        /// </summary>
        public static string RandomSkin {
            get {
                return ResourceManager.GetString("RandomSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting match.
        /// </summary>
        public static string ReadyCheck {
            get {
                return ResourceManager.GetString("ReadyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reroll detected.
        /// </summary>
        public static string Reroll {
            get {
                return ResourceManager.GetString("Reroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting runes.
        /// </summary>
        public static string SettingRunes {
            get {
                return ResourceManager.GetString("SettingRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting summoner&apos;s spells.
        /// </summary>
        public static string SettingSummoners {
            get {
                return ResourceManager.GetString("SettingSummoners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Initialized.
        /// </summary>
        public static string UIInitialized {
            get {
                return ResourceManager.GetString("UIInitialized", resourceCulture);
            }
        }
    }
}
