//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kalus.Properties.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add →.
        /// </summary>
        public static string AddChampionButton {
            get {
                return ResourceManager.GetString("AddChampionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick back champion on unliked roll.
        /// </summary>
        public static string AramRepickChampion {
            get {
                return ResourceManager.GetString("AramRepickChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll until getting a liked champion.
        /// </summary>
        public static string AramRerollForChampion {
            get {
                return ResourceManager.GetString("AramRerollForChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade for liked champion.
        /// </summary>
        public static string AramTradeForChampion {
            get {
                return ResourceManager.GetString("AramTradeForChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        public static string BansOption1 {
            get {
                return ResourceManager.GetString("BansOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and Wait.
        /// </summary>
        public static string BansOption2 {
            get {
                return ResourceManager.GetString("BansOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Time Left.
        /// </summary>
        public static string BansOption3 {
            get {
                return ResourceManager.GetString("BansOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champions List.
        /// </summary>
        public static string ChampionsListHeader {
            get {
                return ResourceManager.GetString("ChampionsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champions.
        /// </summary>
        public static string ChampionsTabHeader {
            get {
                return ResourceManager.GetString("ChampionsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string ConsoleTabHeader {
            get {
                return ResourceManager.GetString("ConsoleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked Champion.
        /// </summary>
        public static string ControlPanelChampionPickLabel {
            get {
                return ResourceManager.GetString("ControlPanelChampionPickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Runes.
        /// </summary>
        public static string ControlPanelChangeRunes {
            get {
                return ResourceManager.GetString("ControlPanelChangeRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemode.
        /// </summary>
        public static string ControlPanelGameModeLabel {
            get {
                return ResourceManager.GetString("ControlPanelGameModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Lite Mode.
        /// </summary>
        public static string ControlPanelLiteModeButton {
            get {
                return ResourceManager.GetString("ControlPanelLiteModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Skin.
        /// </summary>
        public static string ControlPanelRandomSkinButton {
            get {
                return ResourceManager.GetString("ControlPanelRandomSkinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload League Client.
        /// </summary>
        public static string ControlPanelReloadClientButton {
            get {
                return ResourceManager.GetString("ControlPanelReloadClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes.
        /// </summary>
        public static string ControlPanelRunesLabel {
            get {
                return ResourceManager.GetString("ControlPanelRunesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ControlPanelStatus {
            get {
                return ResourceManager.GetString("ControlPanelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Utilities.
        /// </summary>
        public static string ControlPanelUtility {
            get {
                return ResourceManager.GetString("ControlPanelUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty List.
        /// </summary>
        public static string EmptyChampionListButton {
            get {
                return ResourceManager.GetString("EmptyChampionListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string FlashPositionOption1 {
            get {
                return ResourceManager.GetString("FlashPositionOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string FlashPositionOption2 {
            get {
                return ResourceManager.GetString("FlashPositionOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrelevant.
        /// </summary>
        public static string FlashPositionOption3 {
            get {
                return ResourceManager.GetString("FlashPositionOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select random from current role.
        /// </summary>
        public static string NoAvailablePickOption1 {
            get {
                return ResourceManager.GetString("NoAvailablePickOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select random from any role.
        /// </summary>
        public static string NoAvailablePickOption2 {
            get {
                return ResourceManager.GetString("NoAvailablePickOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string NoAvailablePickOption3 {
            get {
                return ResourceManager.GetString("NoAvailablePickOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string NotifyIconOption1 {
            get {
                return ResourceManager.GetString("NotifyIconOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string NotifyIconOption2 {
            get {
                return ResourceManager.GetString("NotifyIconOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string NotifyIconOption3 {
            get {
                return ResourceManager.GetString("NotifyIconOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string OnChampionSelectionOption1 {
            get {
                return ResourceManager.GetString("OnChampionSelectionOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still use automatic pick.
        /// </summary>
        public static string OnChampionSelectionOption2 {
            get {
                return ResourceManager.GetString("OnChampionSelectionOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use selected champion for automatic pick.
        /// </summary>
        public static string OnChampionSelectionOption3 {
            get {
                return ResourceManager.GetString("OnChampionSelectionOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        public static string PicksOption1 {
            get {
                return ResourceManager.GetString("PicksOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and Wait.
        /// </summary>
        public static string PicksOption2 {
            get {
                return ResourceManager.GetString("PicksOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Time Left.
        /// </summary>
        public static string PicksOption3 {
            get {
                return ResourceManager.GetString("PicksOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aram.
        /// </summary>
        public static string PreferenceAram {
            get {
                return ResourceManager.GetString("PreferenceAram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bans.
        /// </summary>
        public static string PreferenceBans {
            get {
                return ResourceManager.GetString("PreferenceBans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Picks.
        /// </summary>
        public static string PreferenceNoAvailablePick {
            get {
                return ResourceManager.GetString("PreferenceNoAvailablePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Champion Selection.
        /// </summary>
        public static string PreferenceOnChampionSelection {
            get {
                return ResourceManager.GetString("PreferenceOnChampionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior on user champion selection before pick phase.
        /// </summary>
        public static string PreferenceOnChampionSelectionDescription {
            get {
                return ResourceManager.GetString("PreferenceOnChampionSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picks.
        /// </summary>
        public static string PreferencePicks {
            get {
                return ResourceManager.GetString("PreferencePicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Skin.
        /// </summary>
        public static string PreferenceRandomSkin {
            get {
                return ResourceManager.GetString("PreferenceRandomSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes.
        /// </summary>
        public static string PreferenceRunes {
            get {
                return ResourceManager.GetString("PreferenceRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string PreferencesTabHeader {
            get {
                return ResourceManager.GetString("PreferencesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner Spells.
        /// </summary>
        public static string PreferenceSummoners {
            get {
                return ResourceManager.GetString("PreferenceSummoners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chroma skins to randomizer.
        /// </summary>
        public static string RandomSkinAddChromas {
            get {
                return ResourceManager.GetString("RandomSkinAddChromas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize skin on champion pick.
        /// </summary>
        public static string RandomSkinOnPick {
            get {
                return ResourceManager.GetString("RandomSkinOnPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Remove.
        /// </summary>
        public static string RemoveChampionButton {
            get {
                return ResourceManager.GetString("RemoveChampionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase page when no available slot.
        /// </summary>
        public static string RunesOverrideOldestPage {
            get {
                return ResourceManager.GetString("RunesOverrideOldestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not set page as active.
        /// </summary>
        public static string RunesPageNotAsActive {
            get {
                return ResourceManager.GetString("RunesPageNotAsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Champions.
        /// </summary>
        public static string SelectedChampionsListHeader {
            get {
                return ResourceManager.GetString("SelectedChampionsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Interval.
        /// </summary>
        public static string SettingCheckInterval {
            get {
                return ResourceManager.GetString("SettingCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close on Client exit.
        /// </summary>
        public static string SettingCloseWithClient {
            get {
                return ResourceManager.GetString("SettingCloseWithClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingLocalization {
            get {
                return ResourceManager.GetString("SettingLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray instead of closing.
        /// </summary>
        public static string SettingMinimizeInsteadOfClosing {
            get {
                return ResourceManager.GetString("SettingMinimizeInsteadOfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Windows start.
        /// </summary>
        public static string SettingOpenOnWindowsStart {
            get {
                return ResourceManager.GetString("SettingOpenOnWindowsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open KALUS window with client.
        /// </summary>
        public static string SettingOpenWithClient {
            get {
                return ResourceManager.GetString("SettingOpenWithClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce to system tray on start-up.
        /// </summary>
        public static string SettingRunInBackground {
            get {
                return ResourceManager.GetString("SettingRunInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTabHeader {
            get {
                return ResourceManager.GetString("SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalus Start/Close behavior.
        /// </summary>
        public static string SettingWindowsBehavior {
            get {
                return ResourceManager.GetString("SettingWindowsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always have snowball in Aram.
        /// </summary>
        public static string SummonersAlwaysSnowball {
            get {
                return ResourceManager.GetString("SummonersAlwaysSnowball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash position :.
        /// </summary>
        public static string SummonersFlashPosition {
            get {
                return ResourceManager.GetString("SummonersFlashPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aram Auto Swap.
        /// </summary>
        public static string UtilityAram {
            get {
                return ResourceManager.GetString("UtilityAram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Champion.
        /// </summary>
        public static string UtilityBan {
            get {
                return ResourceManager.GetString("UtilityBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Champion.
        /// </summary>
        public static string UtilityPick {
            get {
                return ResourceManager.GetString("UtilityPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Check.
        /// </summary>
        public static string UtilityReadyCheck {
            get {
                return ResourceManager.GetString("UtilityReadyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Runes.
        /// </summary>
        public static string UtilityRunes {
            get {
                return ResourceManager.GetString("UtilityRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Summoners.
        /// </summary>
        public static string UtilitySummoners {
            get {
                return ResourceManager.GetString("UtilitySummoners", resourceCulture);
            }
        }
    }
}
